server {
    listen 80;
    server_name 127.0.0.1 localhost;

    location /server-log-insights-tracking/ {
        alias /app/;
        autoindex on;
        add_header Cache-Control "no-cache";

        # Ensure ES modules are served with the correct MIME type
        include /etc/nginx/mime.types;
        types {
            application/javascript  mjs;
        }
    }
}
